### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by julio4**
Spotted some typos in comments, variable and function names while reading through the code base.

### CODE REVIEW

**Review by rodrodros — APPROVED** [review]
So many typos :scream:! Thanks  for your contribution!

**Review by rjnrohit — APPROVED** [review]
Thanks!

**Comment by AlejandroLabourdette** [comment]
Nice! could you also merge develop into this PR so it can pass all tests?.

**Comment by julio4** [comment]
@AlejandroLabourdette Done !

**Review by AlejandroLabourdette — APPROVED** [review]

**Pull request merged**
