### PR TITLE
use nethersolc instead of kudu

### PR DESCRIPTION
**Pull request by murcake**

### CODE REVIEW

**Comment by swapnilraj** [comment]
The files changed shows the macos_10_15/kudu was renamed to linux/nethersolc, is github being stupid here?

**Comment by murcake** [comment]
> The files changed shows that macos_10_15/kudu was renamed to linux/nethersolc, is github being stupid here?

I don't know what happened, perhaps the diff algorithm handles binary files _that_ bad. The tests pass, soo, it must do the right thing

**Comment by murcake** [comment]
@swapnilraj does this pass the ethereum test suite?

**Comment by swapnilraj** [comment]
> @swapnilraj does this pass the ethereum test suite?

For some reason I thought that Greg had run these changes, I just talked to him offline and he confirmed he hadn't.
I'll run them now and let you know.

**Comment by swapnilraj** [comment]
@murcake all tests pass but I did have to use a newer version of isoltest, if you grab the one from develop that should work

**Pull request merged**
