### PR TITLE
add cli tests

### PR DESCRIPTION
**Pull request by murcake**
For now, we just test that all command finish with exit code 0

### CODE REVIEW

**Review by BitBaseBit — APPROVED** [review]

**Comment by JorikSchellekens** [comment]
Is starknet going to be happy if we're deploying large files everytime our ci runs?

**Comment by murcake** [comment]
It wouldn't hurt to ask

**Comment by JorikSchellekens** [comment]
Will you?

**Comment by murcake** [comment]
Yes

**Comment by JorikSchellekens** [comment]
Note for others: Shahar ok'd this

**Pull request merged**
