### PR TITLE
Improve autocompletion feature for CLI

### PR DESCRIPTION
**Pull request by Glitch18**
Optimizes the import statements to improve the CLI response time from 0.9 seconds to 0.05 seconds.

### CODE REVIEW

**Comment by JorikSchellekens** [comment]
can you run `black .` on this dir? Also please add some instructions in the readme on how to get autocomplete working as per this example: https://pip.pypa.io/en/stable/user_guide/#command-completion

**Comment by JorikSchellekens** [comment]
@Glitch18 ran black on this

**Comment by Glitch18** [comment]
Added instructions for setting up autocompletion in `README.md` 
The file also got formatted by `black` upon saving.

**Review by JorikSchellekens — APPROVED** [review]
Beautiful

**Pull request merged**
