### PR TITLE
Remove vendor cairo

### PR DESCRIPTION
**Pull request by murcake**

### CODE REVIEW

**Review by cicr99 — APPROVED** [review]

**Review by BitBaseBit — COMMENTED** [review]
Can we leave the cairo-lang zip file somewhere? It makes following the ERC20 demo much easier because it's all in one place in this repo.

**Comment by murcake** [comment]
> Can we leave the cairo-lang zip file somewhere? It makes following the ERC20 demo much easier because it's all in one place in this repo.

But isn't it just as easy to call `pip install cairo-lang==0.3.1`? If you don't think so, I can leave the file around

**Comment by BitBaseBit** [comment]
> > Can we leave the cairo-lang zip file somewhere? It makes following the ERC20 demo much easier because it's all in one place in this repo.
> 
> But isn't it just as easy to call `pip install cairo-lang==0.3.1`? If you don't think so, I can leave the file around

Yeah that works. Make sure to update the readme for installation, and test it works.

**Review by BitBaseBit — COMMENTED** [review]
LGGTM

**Review by BitBaseBit — APPROVED** [review]

**Pull request merged**
