### PR TITLE
update deployment instruction in docs

### PR DESCRIPTION
**Pull request by jelilat**
The current deployment instruction `warp deploy <path to Cairo contract>` returns an error when you call it. I updated it with the right deployment command.

### CODE REVIEW

**Review by BitBaseBit — CHANGES_REQUESTED** [review]
Please change the commit to alert the user in the CLI that we have used those parameters. And then put it in the docs somewhere.

**Comment by jelilat** [comment]
I'm not sure I understand your comment @BitBaseBit

**Comment by JorikSchellekens** [comment]
@jelilat you can create a "user" on StarkNet, check `warp deploy-account` which deploys a user and creates a file tracking them in your home directory. If there is a `__default__` user in this file it will be used by warp and `--no-wallet` is no longer required. Can you update the readme to include the account deployment steps instead of no-wallet? Also the gateway can be set in an env - would be nice to have that in the readme too.

Thank you for catching this!

**Comment by JorikSchellekens** [comment]
I've updated the readme accordingly. Thanks for the initial pr @jelilat

**Review by JorikSchellekens — APPROVED** [review]
Going to be cheeky and approve this for myself :D

**Comment by jelilat** [comment]
Thanks @JorikSchellekens 

Sorry I wasn't able to get to this sooner.

**Review by swapnilraj — APPROVED** [review]

**Comment by JorikSchellekens** [comment]
Ah np, just appreciate the input!

**Pull request merged**
