### PR TITLE
update cairo dependency -> 0.10.3

### PR DESCRIPTION
**Pull request by rjnrohit**
Removes cairo-format from everywhere as it has bugs related to `;`.

`yarn warplib` was producing invalid cairo files such as `sub_signed.cairo` and some more files .

### CODE REVIEW

**Comment by swapnilraj** [comment]
Can you share some examples of the cairo-format bug?

**Comment by rjnrohit** [comment]
> Can you share some examples of the cairo-format bug?

Update the cairo version in your system to `0.10.3` , checkout to `develop` branch and run 
1. yarn tsc
2. yarn warplib

You would notice an error in `warplib/sub_signed.cairo` file as


Screenshot 2023-01-18 at 12 14 51 PM

**Comment by swapnilraj** [comment]
> > Can you share some examples of the cairo-format bug?
> 
> Update the cairo version in your system to `0.10.3` , checkout to `develop` branch and run
> 
> 1. yarn tsc
> 2. yarn warplib
> 
> You would notice an error in `warplib/sub_signed.cairo` file as
> 
> Screenshot 2023-01-18 at 12 14 51 PM

Right, I see can you open an issue on the cairo repo?
With a small cairo program to recreate this issue

**Comment by swapnilraj** [comment]
Re-pointing this PR to merge into #853 because I need 10.3 environment for some updates

**Pull request merged**
