### PR TITLE
output dir from `.sol/*.cairo` to `.sol.out/*.cairo`

### LINKED ISSUE #822: `bin/warp transpile solc_file -o .`  is not working anymore
`bin/warp transpile solc_file -o .`  is not working anymore, it used to work before. Possibly because of the dir name clash with the solidity file name itself.

```
Error: ENOTDIR: not a directory, open 'order_of_eval.sol/A_sol_abi.json'
    at Object.openSync (node:fs:599:3)
    at Object.writeFileSync (node:fs:2221:35)
    at Object.outputFileSync (/Users/rohit/nmd/warp/node_modules/fs-extra/lib/output-file/index.js:31:15)
    at outputResult (/Users/rohit/nmd/warp/build/io.js:104:12)
    at /Users/rohit/nmd/warp/build/index.js:73:35
    at Array.map (<anonymous>)
    at Command.<anonymous> (/Users/rohit/nmd/warp/build/index.js:72:14)
    at Command.listener [as _actionHa

...
```

### PR DESCRIPTION
**Pull request by rjnrohit**
closes #822
Add .out to output dir of transpile cmd
- [ ] hardhat-warp PR:

### CODE REVIEW

**Comment by swapnilraj** [comment]
This change will require changes to hardhat-warp as well, will merge once the corresponding hardhat-warp change PR is up.

**Comment by JorikSchellekens** [comment]
Why are we introducing this?

**Comment by rjnrohit** [comment]
> Why are we introducing this?

https://demerzelsolutions.slack.com/archives/C03351HQS1Z/p1668087960325449

**Review by piwonskp — APPROVED** [review]

**Comment by JorikSchellekens** [comment]
I'm no longer a fan of using this extension @RohitRanjangit. It's clunky. @swapnilraj suggested banning the `.` case for the `-o` command. I'm worried that banning it will lead to bad UX, but I don't see another good way of doing it.

**Comment by swapnilraj** [comment]
I don't think -o . is as common as you think it is and that's why i don't see it as an issue. Especially if we accompany the ban with a nice message I don't see a problem with it. Open to suggestions

**Comment by rjnrohit** [comment]
As discussed we don't need it anymore

**Pull request closed without merging**
